package ru.sfedu.transportmanagementsystem.entities;

public enum InputKeys {
    CSV, DB, XML,SEND_TRAFFIC ,CHECK_TRAFFIC, CHANGE_TRAFFIC,ADD_BORT,ADD_CARGO,ADD_CLOSEDTRANSPORT,ADD_CONTAINER,ADD_DRIVER,ADD_OPENTRANSPORT,ADD_PLATFORM,ADD_REFRIGERATOR,
    ADD_TENT,ADD_TRAFFIC,ADD_TRANSPORT, GET_BORT,GET_CARGO,GET_CLOSEDTRANSPORT,GET_CONTAINER,GET_DRIVER,GET_OPENTRANSPORT,GET_PLATFORM,GET_REFRIGERATOR,
    GET_TENT,GET_TRAFFIC,GET_TRANSPORT,UPD_BORT,UPD_CARGO,UPD_CLOSEDTRANSPORT,UPD_CONTAINER,UPD_DRIVER,UPD_OPENTRANSPORT,UPD_PLATFORM,UPD_REFRIGERATOR,
    UPD_TENT,UPD_TRAFFIC,UPD_TRANSPORT,DEL_BORT,DEL_CARGO,DEL_CLOSEDTRANSPORT,DEL_CONTAINER,DEL_DRIVER,DEL_OPENTRANSPORT,DEL_PLATFORM,DEL_REFRIGERATOR,
    DEL_TENT,DEL_TRAFFIC,DEL_TRANSPORT
}
